version: '3'
services:
  api:
    container_name: myseriesapi
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
  mongo:
    container_name: myseriesdb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data:/data/db

volumes:
  data: